version: '3'
services:
  flask-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    environment:
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=mysql-db
      - DB_NAME=manguonmo2023
      - IS_DEPLOY=true
      - HOST=0.0.0.0
      - CORS_URL=*
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=manguonmo2023
    volumes:
      - manguonmo2023-db-data:/var/lib/mysql

volumes:
  manguonmo2023-db-data:

